**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [11]:
import numpy as np

In [122]:
n = np.arange(0, 10)
n 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
b = np.sort(n)[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [152]:
a = np.diag(np.arange(1, 10, 1), k=0)
a

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [159]:
b = np.asarray(a)
np.trace(b)

45

**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [20]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [13]:
from numpy import linalg

In [21]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [22]:
np.allclose(np.dot(a, linalg.solve(a, b)), b)

True